version: '3.7'
services:
  web:
    build:
      context: ./
      dockerfile: ./app/Dockerfile
    #command: sh -c ./financier_web_main/ ls
    command: python ./main/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    container_name: site_check_django