# pull official base image
FROM python:3.10-alpine3.17
# set work directory
WORKDIR /usr/src/app
# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
# install dependencies
RUN pip install --upgrade pip
COPY ./back/requirements.txt ./
RUN pip install --requirement requirements.txt
# copy project
COPY ./back .
COPY ./supervisor ./supervisor

#apk update && apk add --no-cache supervisor openssh

RUN apk update && apk add --no-cache supervisor openssh
COPY ./supervisor/supervisord.conf /etc/supervisord.conf
RUN mkdir -p /run/daphne

ENTRYPOINT [ "sh", "/usr/src/app/docker-entrypoint_prod.sh" ]
#ENTRYPOINT ["tail", "-f", "/dev/null"]